-- Insert sample products for MD Electronics
WITH category_ids AS (
  SELECT id, slug FROM categories
),
brand_ids AS (
  SELECT id, slug FROM brands
)
INSERT INTO products (
  id, name, slug, description, short_description, price, original_price, 
  stock_quantity, sku, images, specifications, warranty_info, 
  is_active, is_featured, category_id, brand_id, created_at, updated_at
) VALUES
-- Refrigerators
(uuid_generate_v4(), 'Samsung French Door Refrigerator 28 cu ft', 'samsung-french-door-28', 
 'Experience the ultimate in food preservation with this spacious French door refrigerator featuring Twin Cooling Plus technology, FlexZone drawer, and Energy Star certification.', 
 'Spacious French door refrigerator with advanced cooling technology', 
 1299.99, 1599.99, 15, 'REF-SAM-001',
 ARRAY['/placeholder.svg?height=400&width=400', '/placeholder.svg?height=400&width=400'],
 '{"capacity": "28 cu ft", "type": "French Door", "energy_rating": "Energy Star", "features": ["Twin Cooling Plus", "FlexZone Drawer", "LED Lighting", "Ice Maker"]}',
 '2 years manufacturer warranty',
 true, true, 
 (SELECT id FROM category_ids WHERE slug = 'refrigerators'),
 (SELECT id FROM brand_ids WHERE slug = 'samsung'),
 now(), now()),

(uuid_generate_v4(), 'LG Side-by-Side Refrigerator 26 cu ft', 'lg-side-by-side-26',
 'Modern side-by-side refrigerator with InstaView Door-in-Door technology, smart connectivity, and efficient linear compressor for optimal performance.',
 'Smart side-by-side refrigerator with InstaView technology',
 1199.99, 1399.99, 12, 'REF-LG-002',
 ARRAY['/placeholder.svg?height=400&width=400', '/placeholder.svg?height=400&width=400'],
 '{"capacity": "26 cu ft", "type": "Side-by-Side", "energy_rating": "Energy Star", "features": ["InstaView Door-in-Door", "Smart ThinQ", "Linear Compressor", "Water Dispenser"]}',
 '2 years manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'refrigerators'),
 (SELECT id FROM brand_ids WHERE slug = 'lg'),
 now(), now()),

-- Ovens
(uuid_generate_v4(), 'Bosch Built-in Electric Oven 30"', 'bosch-builtin-electric-30',
 'Professional-grade built-in electric oven with European convection, self-cleaning function, and precise temperature control for perfect cooking results.',
 'Professional built-in electric oven with convection',
 899.99, 1099.99, 8, 'OVN-BSH-001',
 ARRAY['/placeholder.svg?height=400&width=400', '/placeholder.svg?height=400&width=400'],
 '{"size": "30 inch", "type": "Built-in Electric", "capacity": "4.6 cu ft", "features": ["European Convection", "Self-Cleaning", "Touch Control", "Sabbath Mode"]}',
 '2 years manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'ovens'),
 (SELECT id FROM brand_ids WHERE slug = 'bosch'),
 now(), now()),

(uuid_generate_v4(), 'Whirlpool Gas Range 30"', 'whirlpool-gas-range-30',
 'Versatile gas range with 5-burner cooktop, convection oven, and AccuBake temperature management system for consistent cooking results.',
 'Gas range with 5-burner cooktop and convection oven',
 749.99, 899.99, 10, 'OVN-WHP-002',
 ARRAY['/placeholder.svg?height=400&width=400', '/placeholder.svg?height=400&width=400'],
 '{"size": "30 inch", "type": "Gas Range", "burners": 5, "features": ["Convection Oven", "AccuBake System", "Storage Drawer", "Electronic Ignition"]}',
 '1 year manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'ovens'),
 (SELECT id FROM brand_ids WHERE slug = 'whirlpool'),
 now(), now()),

-- Televisions
(uuid_generate_v4(), 'Samsung 65" QLED 4K Smart TV', 'samsung-65-qled-4k',
 'Immerse yourself in stunning 4K entertainment with Quantum Dot technology, HDR10+ support, and Tizen smart platform with voice control.',
 'Premium 65" QLED 4K Smart TV with Quantum Dot technology',
 1499.99, 1799.99, 20, 'TV-SAM-001',
 ARRAY['/placeholder.svg?height=400&width=400', '/placeholder.svg?height=400&width=400'],
 '{"screen_size": "65 inch", "resolution": "4K UHD", "display_type": "QLED", "features": ["Quantum Dot", "HDR10+", "Tizen OS", "Voice Control", "Gaming Mode"]}',
 '1 year manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'televisions'),
 (SELECT id FROM brand_ids WHERE slug = 'samsung'),
 now(), now()),

(uuid_generate_v4(), 'Sony 55" OLED 4K Smart TV', 'sony-55-oled-4k',
 'Experience perfect blacks and infinite contrast with OLED technology, Dolby Vision, and Google TV platform for endless entertainment.',
 'Premium 55" OLED 4K Smart TV with perfect blacks',
 1299.99, 1599.99, 15, 'TV-SNY-002',
 ARRAY['/placeholder.svg?height=400&width=400', '/placeholder.svg?height=400&width=400'],
 '{"screen_size": "55 inch", "resolution": "4K UHD", "display_type": "OLED", "features": ["Perfect Blacks", "Dolby Vision", "Google TV", "Voice Remote", "Gaming Features"]}',
 '1 year manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'televisions'),
 (SELECT id FROM brand_ids WHERE slug = 'sony'),
 now(), now()),

-- Air Conditioners
(uuid_generate_v4(), 'LG 12000 BTU Window AC Unit', 'lg-12000-btu-window-ac',
 'Efficient window air conditioner with dual inverter technology, smart connectivity, and energy-saving features for optimal comfort.',
 'Energy-efficient 12000 BTU window AC with smart features',
 449.99, 549.99, 25, 'AC-LG-001',
 ARRAY['/placeholder.svg?height=400&width=400', '/placeholder.svg?height=400&width=400'],
 '{"capacity": "12000 BTU", "type": "Window Unit", "room_size": "550 sq ft", "features": ["Dual Inverter", "Smart ThinQ", "Energy Star", "Remote Control"]}',
 '2 years manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'air-conditioners'),
 (SELECT id FROM brand_ids WHERE slug = 'lg'),
 now(), now()),

(uuid_generate_v4(), 'Samsung 18000 BTU Split AC System', 'samsung-18000-btu-split',
 'Powerful split air conditioning system with WindFree technology, smart controls, and whisper-quiet operation for large spaces.',
 'Powerful 18000 BTU split AC with WindFree technology',
 899.99, 1099.99, 12, 'AC-SAM-002',
 ARRAY['/placeholder.svg?height=400&width=400', '/placeholder.svg?height=400&width=400'],
 '{"capacity": "18000 BTU", "type": "Split System", "room_size": "750 sq ft", "features": ["WindFree Technology", "Smart Control", "Quiet Operation", "Energy Efficient"]}',
 '3 years manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'air-conditioners'),
 (SELECT id FROM brand_ids WHERE slug = 'samsung'),
 now(), now()),

-- Washing Machines
(uuid_generate_v4(), 'Whirlpool Top Load Washer 4.3 cu ft', 'whirlpool-top-load-43',
 'Reliable top-load washing machine with Adaptive Wash technology, multiple wash cycles, and energy-efficient operation.',
 'Reliable top-load washer with Adaptive Wash technology',
 599.99, 699.99, 18, 'WM-WHP-001',
 ARRAY['/placeholder.svg?height=400&width=400', '/placeholder.svg?height=400&width=400'],
 '{"capacity": "4.3 cu ft", "type": "Top Load", "features": ["Adaptive Wash", "12 Wash Cycles", "Energy Star", "Deep Water Wash"]}',
 '2 years manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'washing-machines'),
 (SELECT id FROM brand_ids WHERE slug = 'whirlpool'),
 now(), now()),

(uuid_generate_v4(), 'LG Front Load Washer 4.5 cu ft', 'lg-front-load-45',
 'Advanced front-load washer with TurboWash technology, steam cleaning, and smart connectivity for superior cleaning performance.',
 'Advanced front-load washer with TurboWash technology',
 799.99, 949.99, 14, 'WM-LG-002',
 ARRAY['/placeholder.svg?height=400&width=400', '/placeholder.svg?height=400&width=400'],
 '{"capacity": "4.5 cu ft", "type": "Front Load", "features": ["TurboWash", "Steam Clean", "Smart ThinQ", "14 Wash Programs"]}',
 '2 years manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'washing-machines'),
 (SELECT id FROM brand_ids WHERE slug = 'lg'),
 now(), now()),

-- Deep Freezers
(uuid_generate_v4(), 'Haier Chest Freezer 7.1 cu ft', 'haier-chest-freezer-71',
 'Spacious chest freezer with energy-efficient operation, adjustable temperature control, and removable storage baskets.',
 'Energy-efficient 7.1 cu ft chest freezer',
 299.99, 349.99, 22, 'FRZ-HAI-001',
 ARRAY['/placeholder.svg?height=400&width=400', '/placeholder.svg?height=400&width=400'],
 '{"capacity": "7.1 cu ft", "type": "Chest Freezer", "features": ["Energy Star", "Adjustable Temperature", "Storage Baskets", "Lock & Key"]}',
 '1 year manufacturer warranty',
 true, false,
 (SELECT id FROM category_ids WHERE slug = 'deep-freezers'),
 (SELECT id FROM brand_ids WHERE slug = 'haier'),
 now(), now()),

(uuid_generate_v4(), 'Electrolux Upright Freezer 14 cu ft', 'electrolux-upright-14',
 'Large upright freezer with frost-free operation, LED lighting, and multiple storage compartments for organized freezing.',
 'Large 14 cu ft upright freezer with frost-free operation',
 699.99, 799.99, 8, 'FRZ-ELX-002',
 ARRAY['/placeholder.svg?height=400&width=400', '/placeholder.svg?height=400&width=400'],
 '{"capacity": "14 cu ft", "type": "Upright Freezer", "features": ["Frost-Free", "LED Lighting", "Adjustable Shelves", "Door Alarm"]}',
 '2 years manufacturer warranty',
 true, true,
 (SELECT id FROM category_ids WHERE slug = 'deep-freezers'),
 (SELECT id FROM brand_ids WHERE slug = 'electrolux'),
 now(), now());
